version: '3'

services:
  flask_server:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    image: protonx/ai-devs-02:buiquangdat1710-server-v1.0 # TODO 1: Nhập tên server image của bạn.
    container_name: flask_server
    platform: linux/amd64
    volumes:
      - ./:/app
    ports:
      - "5002:5002" # TODO 2: Chuyển tiếp cổng 5002 vào 5002
    environment:
      - FLASK_ENV=development
      - API_TOKEN=None# TODO 3: Nhập API_KEY từ Together AI
    networks:
      - my_network

  streamlit_client:
    build:
      context: .
      dockerfile: ./client.Dockerfile
    image: protonx/ai-devs-02:buiquangdat1710-client-v1.0 # TODO 4: Nhập tên client image của bạn.
    container_name: streamlit_client
    platform: linux/amd64
    volumes:
      - ./:/app
    ports:
      - "8501:8501" # TODO 5: Chuyển tiếp cổng 8501 vào 8501
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
